# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
#open_collective: hostctl # Replace with a single Open Collective username
ko_fi: guumaster
custom: ['https://www.buymeacoffee.com/guumaster' ]
